# Default values for schemes.
replicaCount: 1
image: schemes-commander:latest
pullPolicy: IfNotPresent
antiAffinity:
  weight: 80
  apps:
    - portal
    - identity
service:
  name: schemes-commander
  type: NodePort
  externalPort: 80
  internalPort: 80
env:
  IDENTITY_URL: http://identity.midnight-lizard.online
  ALLOWED_ORIGINS: "\
    http://midnight-lizard.org,\
    https://midnight-lizard.org,\
    http://www.midnight-lizard.org,\
    https://www.midnight-lizard.org"
  SCHEMES_QUEUE_CONFIG: |-
    {
      "TopicName": "schemes-requests-a",
      "ProducerSettings": {
          "bootstrap.servers": "bootstrap.kafka:9092"
        }
    }